version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mountainclimber
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      #初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      #永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      #設定ファイル
      - .db/mysql_cnf/my.cnf:/etc/mysql/conf.d/my.cnf

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db

